[package]
name = "luhn"
version = "0.1.0"
edition = "2021"
authors = ["Fabian Bergstr√∂m <fabian.bergstrom@kivra.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "luhn"
crate-type = ["dylib"]

[dependencies]
rustler = "0.26.0"
